version: 2.1
jobs:
  build:
    docker:
      - image: cimg/base:2023.12

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build and Push application Docker image
          command: |
            TAG=1.0.$CIRCLE_BUILD_NUM
            docker run --privileged --rm tonistiigi/binfmt --install all
            docker build --platform linux/arm64 -t cybercastle/raspberry-os:$TAG .
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
            docker push cybercastle/raspberry-os:$TAG
